name: validate
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  unit-tests:
    runs-on: macos-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Load AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.23.0
        with:
          api-level: 30
          arch: x86_64
          target: default
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Run Tests
        uses: ReactiveCircus/android-emulator-runner@v2.23.0
        with:
          api-level: 30
          arch: x86_64
          target: default
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :kotlin-audio:connectedCheck
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # run this step even if previous step failed
        with:
          name: unit-tests-report # Name of the check run which will be created
          path: kotlin-audio/build/outputs/androidTest-results/**/*.xml # Path to test results
          reporter: java-junit # Format of test results
  build-sample:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build Sample App
        run: ./gradlew :kotlin-audio-sample:assembleDebug
