name: validate
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: ./gradlew :kotlin-audio-sample:connectedAndroidTest