name: validate
on: [push]
jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :kotlin-audio:connectedCheck
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # run this step even if previous step failed
        with:
          name: unit-tests-report # Name of the check run which will be created
          path: kotlin-audio/build/outputs/androidTest-results/**/*.xml # Path to test results
          reporter: java-junit # Format of test results
  build-sample:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Tests
        run: ./gradlew :kotlin-audio-sample:assembleDebug
